# Site settings
title: Al-Irtibaat
header-img: img/home-bg.png
email: jmstricker93@gmail.com
copyright_name: jmstrick93
description: > # this means to ignore newlines until "baseurl:"
  Rebooting my career without formatting my hard drive.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jmstrick93
learn_profile: jmstrick93
email_username: jmstricker93@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
